# Generated by Django 5.0.7 on 2024-08-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0003_rename_resource_rol_permission_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='icono',
            field=models.CharField(default='', max_length=30),
        ),
    ]
