# Generated by Django 5.0.7 on 2024-08-10 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0004_resource_icono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='icono',
            new_name='icon',
        ),
    ]
