# Generated by Django 5.0.7 on 2024-08-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0005_rename_icono_resource_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('message', models.TextField()),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('request_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'log_base',
                'verbose_name_plural': 'log_base',
            },
        ),
    ]
