# Generated by Django 5.0.7 on 2024-12-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='row_id',
            field=models.IntegerField(null=True),
        ),
    ]
